export const EMPLOYE_LIST_REQUEST = 'EMPLOYE_LIST_REQUEST'
export const EMPLOYE_LIST_SUCCESS = 'EMPLOYE_LIST_SUCCESS'
export const EMPLOYE_LIST_FAIL = 'EMPLOYE_LIST_FAIL'

export const EMPLOYE_DELETE_REQUEST = 'EMPLOYE_DELETE_REQUEST'
export const EMPLOYE_DELETE_SUCCESS = 'EMPLOYE_DELETE_SUCCESS'
export const EMPLOYE_DELETE_FAIL = 'EMPLOYE_DELETE_FAIL'

export const EMPLOYE_CREATE_REQUEST = 'EMPLOYE_CREATE_REQUEST'
export const EMPLOYE_CREATE_SUCCESS = 'EMPLOYE_CREATE_SUCCESS'
export const EMPLOYE_CREATE_FAIL = 'EMPLOYE_CREATE_FAIL'

export const EMPLOYE_DEMANDE_REQUEST = 'EMPLOYE_DEMANDE_REQUEST'
export const EMPLOYE_DEMANDE_SUCCESS = 'EMPLOYE_DEMANDE_SUCCESS'
export const EMPLOYE_DEMANDE_FAIL = 'EMPLOYE_DEMANDE_FAIL'

export const EMPLOYE_UPDATE_REQUEST = 'EMPLOYE_UPDATE_REQUEST'
export const EMPLOYE_UPDATE_SUCCESS = 'EMPLOYE_UPDATE_SUCCESS'
export const EMPLOYE_UPDATE_FAIL = 'EMPLOYE_UPDATE_FAIL'

export const EMPLOYE_ACCEPT_REQUEST = 'EMPLOYE_ACCEPT_REQUEST'
export const EMPLOYE_ACCEPT_SUCCESS = 'EMPLOYE_ACCEPT_SUCCESS'
export const EMPLOYE_ACCEPT_FAIL = 'EMPLOYE_ACCEPT_FAIL'

export const EMPLOYE_DESACTIVER_REQUEST = 'EMPLOYE_DESACTIVER_REQUEST'
export const EMPLOYE_DESACTIVER_SUCCESS = 'EMPLOYE_DESACTIVER_SUCCESS'
export const EMPLOYE_DESACTIVER_FAIL = 'EMPLOYE_DESACTIVER_FAIL'

export const EMPLOYE_STATE_REQUEST = 'EMPLOYE_STATE_REQUEST'
