export const ORGANISME_LIST_REQUEST = 'ORGANISME_LIST_REQUEST'
export const ORGANISME_LIST_SUCCESS = 'ORGANISME_LIST_SUCCESS'
export const ORGANISME_LIST_FAIL = 'ORGANISME_LIST_FAIL'

export const ORGANISME_REGISTER_REQUEST = 'ORGANISME_REGISTER_REQUEST'
export const ORGANISME_REGISTER_SUCCESS = 'ORGANISME_REGISTER_SUCCESS'
export const ORGANISME_REGISTER_FAIL = 'ORGANISME_REGISTER_FAIL'

export const ORGANISME_CREATE_REQUEST = 'ORGANISME_CREATE_REQUEST'
export const ORGANISME_CREATE_SUCCESS = 'ORGANISME_CREATE_SUCCESS'
export const ORGANISME_CREATE_FAIL = 'ORGANISME_CREATE_FAIL'

export const ORGANISME_UPDATE_REQUEST = 'ORGANISME_UPDATE_REQUEST'
export const ORGANISME_UPDATE_SUCCESS = 'ORGANISME_UPDATE_SUCCESS'
export const ORGANISME_UPDATE_FAIL = 'ORGANISME_UPDATE_FAIL'

export const ORGANISME_DELETE_REQUEST = 'ORGANISME_DELETE_REQUEST'
export const ORGANISME_DELETE_SUCCESS = 'ORGANISME_DELETE_SUCCESS'
export const ORGANISME_DELETE_FAIL = 'ORGANISME_DELETE_FAIL'

export const ORGANISME_STATE_REQUEST = 'ORGANISME_STATE_REQUEST'
