export const RESERVATION_CREATE_REQUEST = 'RESERVATION_CREATE_REQUEST'
export const RESERVATION_CREATE_SUCCESS = 'RESERVATION_CREATE_SUCCESS'
export const RESERVATION_CREATE_FAIL = 'RESERVATION_CREATE_FAIL'

export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST'
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS'
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL'

export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST'
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS'
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL'

export const RESERVATION_LIBERER_REQUEST = 'RESERVATION_LIBERER_REQUEST'
export const RESERVATION_LIBERER_SUCCESS = 'RESERVATION_LIBERER_SUCCESS'
export const RESERVATION_LIBERER_FAIL = 'RESERVATION_LIBERER_FAIL'

export const RESERVATION_ACCEPT_REQUEST = 'RESERVATION_ACCEPT_REQUEST'
export const RESERVATION_ACCEPT_SUCCESS = 'RESERVATION_ACCEPT_SUCCESS'
export const RESERVATION_ACCEPT_FAIL = 'RESERVATION_ACCEPT_FAIL'

export const RESERVATION_UPDATE_REQUEST = 'RESERVATION_UPDATE_REQUEST'
export const RESERVATION_UPDATE_SUCCESS = 'RESERVATION_UPDATE_SUCCESS'
export const RESERVATION_UPDATE_FAIL = 'RESERVATION_UPDATE_FAIL'

export const RESERVATION_DISPONIBILITE_REQUEST = 'RESERVATION_DISPONIBILITE_REQUEST'
export const RESERVATION_DISPONIBILITE_SUCCESS = 'RESERVATION_DISPONIBILITE_SUCCESS'
export const RESERVATION_DISPONIBILITE_FAIL = 'RESERVATION_DISPONIBILITE_FAIL'

export const RESERVATION_STATE_REQUEST = 'RESERVATION_STATE_REQUEST'
