export const RESSOURCE_LIST_REQUEST = 'RESSOURCE_LIST_REQUEST'
export const RESSOURCE_LIST_SUCCESS = 'RESSOURCE_LIST_SUCCESS'
export const RESSOURCE_LIST_FAIL = 'RESSOURCE_LIST_FAIL'

export const RESSOURCE_ADMIN_REQUEST = 'RESSOURCE_ADMIN_REQUEST'
export const RESSOURCE_ADMIN_SUCCESS = 'RESSOURCE_ADMIN_SUCCESS'
export const RESSOURCE_ADMIN_FAIL = 'RESSOURCE_ADMIN_FAIL'

export const RESSOURCE_CREATE_REQUEST = 'RESSOURCE_CREATE_REQUEST'
export const RESSOURCE_CREATE_SUCCESS = 'RESSOURCE_CREATE_SUCCESS'
export const RESSOURCE_CREATE_FAIL = 'RESSOURCE_CREATE_FAIL'

export const RESSOURCE_UPDATE_REQUEST = 'RESSOURCE_UPDATE_REQUEST'
export const RESSOURCE_UPDATE_SUCCESS = 'RESSOURCE_UPDATE_SUCCESS'
export const RESSOURCE_UPDATE_FAIL = 'RESSOURCE_UPDATE_FAIL'

export const RESSOURCE_DELETE_REQUEST = 'RESSOURCE_DELETE_REQUEST'
export const RESSOURCE_DELETE_SUCCESS = 'RESSOURCE_DELETE_SUCCESS'
export const RESSOURCE_DELETE_FAIL = 'RESSOURCE_DELETE_FAIL'

export const RESSOURCE_STATE_REQUEST = 'RESSOURCE_STATE_REQUEST'

export const RESSOURCE_CATEGORIE_REQUEST = 'RESSOURCE_CATEGORIE_REQUEST'
export const RESSOURCE_CATEGORIE_SUCCESS = 'RESSOURCE_CATEGORIE_SUCCESS'
export const RESSOURCE_CATEGORIE_FAIL = 'RESSOURCE_CATEGORIE_FAIL'

export const RESSOURCE_RESERVATION_REQUEST = 'RESSOURCE_RESERVATION_REQUEST'
export const RESSOURCE_RESERVATION_SUCCESS = 'RESSOURCE_RESERVATION_SUCCESS'
export const RESSOURCE_RESERVATION_FAIL = 'RESSOURCE_RESERVATION_FAIL'
