export const SALLE_LIST_REQUEST = 'SALLE_LIST_REQUEST'
export const SALLE_LIST_SUCCESS = 'SALLE_LIST_SUCCESS'
export const SALLE_LIST_FAIL = 'SALLE_LIST_FAIL'

export const SALLE_CREATE_REQUEST = 'SALLE_CREATE_REQUEST'
export const SALLE_CREATE_SUCCESS = 'SALLE_CREATE_SUCCESS'
export const SALLE_CREATE_FAIL = 'SALLE_CREATE_FAIL'

export const SALLE_UPDATE_REQUEST = 'SALLE_UPDATE_REQUEST'
export const SALLE_UPDATE_SUCCESS = 'SALLE_UPDATE_SUCCESS'
export const SALLE_UPDATE_FAIL = 'SALLE_UPDATE_FAIL'

export const SALLE_DELETE_REQUEST = 'SALLE_DELETE_REQUEST'
export const SALLE_DELETE_SUCCESS = 'SALLE_DELETE_SUCCESS'
export const SALLE_DELETE_FAIL = 'SALLE_DELETE_FAIL'

export const SALLE_STATE_REQUEST = 'SALLE_STATE_REQUEST'
